[package]
name = "sym"
authors = ["Basile Clement <basile.clement@inria.fr>"]
license = "Apache-2.0"
version = "0.1.0"
edition = "2018"

[dependencies]
fxhash = "0.2"
log = "0.4"
num = "0.2"
itertools = "0.8"

[dev-dependencies]
proptest = "0.9"

[features]
default = []
ignore_collisions = []
verify = []
